### ISSUE TITLE
当悬浮框出现在浏览器窗口旁边的时候.页面出现了滚动条.

### ISSUE THREAD

**Issue by canyanol650** [fh332393900/threejs-demo#1]
如图
![image](https://github.com/fh332393900/threejs-demo/assets/42194280/54719a12-9d71-47b2-ac35-afe4223a01d0)

**Comment by fh332393900** [comment]
给body加了个overflow: hidden

**Comment by fh332393900** [comment]
给body加了个overflow: hidden
